### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by hugoferreira** [JLoureir0/reactIDE#1]
Following the instructions result in this error (most possibly the `mqtt` module is missing from the `package.json`

```
> vpl@0.1.0 start /Users/bytter/Documents/Development/students/reactIDE
> opn public/main.html && node server.js

module.js:559
    throw err;
    ^

Error: Cannot find module 'mqtt'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bytter/Documents/Development/students/reactIDE/block.js:1:76)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vpl@0.1.0 start: `opn public/main.html && node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vpl@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by JLoureir0** [comment]
The package.json that contained the mqtt module got lost with merges. Fixed in the commit [55ed29ec](https://github.com/JLoureir0/reactIDE/commit/55ed29ec32f47d3fd0e6408cd7d8459922e3698c).
